services:
  big-downloader:
    build: .
    container_name: big-downloader
    ports:
      - "127.0.0.1:5555:5555"
    volumes:
      # Persister les téléchargements sur votre machine
      - ./downloads:/app/downloads
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - IN_DOCKER=1
